"""create fornecedorestable

Revision ID: c533c3342cd0
Revises: eec2366b8b17
Create Date: 2026-08-27 16:23:58.850721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c533c3342cd0'
down_revision: Union[str, Sequence[str], None] = 'eec2366b8b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razao_social', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fornecedores_cnpj'), 'fornecedores', ['cnpj'], unique=True)
    op.create_index(op.f('ix_fornecedores_id'), 'fornecedores', ['id'], unique=False)
    op.add_column('produtos', sa.Column('fornecedor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produtos', 'fornecedores', ['fornecedor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'fornecedor_id')
    op.drop_index(op.f('ix_fornecedores_id'), table_name='fornecedores')
    op.drop_index(op.f('ix_fornecedores_cnpj'), table_name='fornecedores')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
