"""add categoria_id to produtos

Revision ID: eec2366b8b17
Revises: 61e35f06ace2
Create Date: 2026-08-18 15:38:09.294353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec2366b8b17'
down_revision: Union[str, Sequence[str], None] = '61e35f06ace2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'produtos', 'categorias', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'categoria_id')
    # ### end Alembic commands ###
